name: Build Mager Binary

on:
  workflow_dispatch:

jobs:
  build-release-artifacts:
    name: "Build ${{ matrix.php-version }} with ${{ matrix.release }} on ${{ matrix.runner }}"
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        release:
          - "linux-x86_64"
          - "linux-aarch64"
          - "macos-x86_64"
          - "macos-aarch64"
        php-version:
          - "8.3.12"
        runner:
          - "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: pecl, composer
          extensions: curl, openssl, mbstring, iconv, ctype
          ini-values: memory_limit=-1

      - name: "Cache composer packages"
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php

      - name: Download Micro With ${{ matrix.php-version }}-${{ matrix-release }}
        run: |
          mkdir downloads
          wget https://dl.static-php.dev/static-php-cli/bulk/php-${{ matrix.php-version }}-${{ matrix-release }}.tar.gz -O downloads/php-${{ matrix.php-version }}-${{ matrix-release }}.tar.gz
          tar -xvzf downloads/php-${{ matrix.php-version }}-${{ matrix.release }}.tar.gz --directory downloads

      - name: "Install Dependencies"
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: "Build Phar"
        run: composer compile

      - name: "Bundle release"
        run: |
          mkdir release
          cat downloads/micro.sfx build/mager.phar > release/mager-${{ matrix.release }} && chmod +x release/mager-${{ matrix.release }}

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: mager-${{ matrix.release }}
          path: |
            release/mager-${{ matrix.release }}
          if-no-files-found: error